# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-16 13:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('moreinfo', models.TextField()),
                ('createddate', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('inprogress', 'inprogress'), ('completed', 'completed')], default='draft', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='OwnUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=250)),
                ('role1', models.CharField(choices=[('aspirant', 'aspirant'), ('recruiter', 'recruiter')], max_length=30)),
                ('applied_jobs', models.ManyToManyField(blank=True, null=True, to='recruitmentprocess.Job')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recruitment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('createddate', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('inprogress', 'inprogress'), ('completed', 'completed')], default='draft', max_length=250)),
                ('startdate', models.DateField(blank=True)),
                ('enddate', models.DateField(blank=True)),
                ('aspirants', models.ManyToManyField(blank=True, null=True, to='recruitmentprocess.OwnUser')),
                ('createdby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('jobs', models.ManyToManyField(to='recruitmentprocess.Job')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='languages',
            field=models.ManyToManyField(to='recruitmentprocess.Language'),
        ),
    ]
