# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-09 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('age', models.IntegerField()),
                ('dob', models.DateField()),
                ('created', models.DateTimeField()),
                ('cust_type', models.CharField(choices=[('g', 'GOLD'), ('s', 'silver'), ('n', 'NORMAL'), ('b', 'BRONZE')], max_length=2)),
            ],
        ),
    ]
