# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-11 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1000)),
                ('createdatetime', models.DateTimeField(auto_now_add=True)),
                ('modifydatetime', models.DateTimeField(auto_now=True)),
                ('status_code', models.CharField(max_length=5)),
            ],
        ),
    ]
