# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-11 04:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesttracker',
            name='status_code',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
