# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-04 06:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('duration', models.IntegerField()),
                ('fee', models.IntegerField()),
                ('starttime', models.CharField(max_length=50)),
                ('endtime', models.CharField(max_length=50)),
                ('enddate', models.DateField()),
                ('startdate', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'DRAFT'), ('inprogress', 'INPROGRESS'), ('complete', 'COMPLETE')], max_length=20)),
                ('info', models.TextField()),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Instructor')),
            ],
        ),
    ]
