# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-31 03:17
from __future__ import unicode_literals

import app1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20180331_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phonenumber',
            field=models.CharField(max_length=12, validators=[app1.models.validate_phone]),
        ),
    ]
