# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-31 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20180331_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='emailaddress',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
