# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-15 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('cost', models.IntegerField(max_length=250)),
                ('noofbeds', models.CharField(choices=[('1', 'Single bedroom'), ('2', 'Single bedroom'), ('3', 'Single bedroom')], max_length=2)),
                ('type', models.CharField(max_length=250)),
            ],
        ),
    ]
