# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-17 05:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('sales_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField()),
                ('status', models.CharField(choices=[('d', 'DRAFT'), ('i', 'INPROGRESS'), ('c', 'COMPLETE')], max_length=1)),
                ('date', models.DateField()),
                ('completed_date', models.DateTimeField()),
                ('delivered', models.BooleanField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Customer')),
                ('products', models.ManyToManyField(to='app1.Product')),
            ],
        ),
    ]
