# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-17 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_product_salesorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Withprimarykey',
            fields=[
                ('name', models.CharField(max_length=250, primary_key=True, serialize=False)),
            ],
        ),
    ]
