# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-17 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_auto_20180317_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='desc',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('d', 'DRAFT'), ('i', 'INPROGRESS'), ('c', 'COMPLETE')], default='d', max_length=1),
        ),
    ]
