# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-17 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_auto_20180317_0533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
