# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-17 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_auto_20180317_0548'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
